server:
    port: 8080
    servlet.context-path: /itemService
    

spring:
     datasource: 
               url: jdbc:h2:~/test 
               driverClassName: org.h2.Driver  
               username: sa  
               password: sa
     h2:
     console:
       enabled: true
     
     jpa: 
     show-sql: true
     hibernate.ddl-auto: update
     properties:
        hibernate:
           dialect: org.hibernate.dialect.H2Dialect
     application: 
               name: Item-Service

eureka: 
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://localhost:8761/eureka/
    
 
ribbon:
    eureka:
        enabled: true